### ISSUE TITLE
Unable to install the package 

### ISSUE THREAD

**Issue by lenaleno** [aaronrkaufman/compactness#2]
Thank you very much for making this package. 
I am not sure why I can't seem to install this package. I am currently using R 3.6.1. 
I have the following error, and it would be really helpful if I can get some advice on how to resolve this issue. 

* installing *source* package ‘compactness’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/imager/libs/imager.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/imager/libs/imager.so, 6): Library not loaded: /opt/X11/lib/libX11.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/imager/libs/imager.so
  Reason: image not found
Calls: <Anonymous> ... namespaceImport -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘compactness’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/compactness’
Error: Failed to install 'compactness' from GitHub:
  (converted from warning) installation of package ‘/var/folders/_c/hv1_yng14jgc1bhswl88xmbc0000gn/T//RtmpNXsV5W/filee5212b63a175/compactness_1.0.6.tar.gz’ had non-zero exit status

**Comment by aaron-horowitz** [comment]
FYI, it looks like you may be missing an imager dependency. Imager page should give you some ideas on how to fix, depending on whether you are using a mac or linux. I'd guess it's xquartz based on your error.
https://dahtah.github.io/imager/index.html#dependencies

**Comment by lenaleno** [comment]
thank you for your reply! The issue has been resolved.
