### ISSUE TITLE
Mechanism for detecting name column doesnt work with 2 column datasets

### ISSUE THREAD

**Issue by aaron-horowitz** [aaronrkaufman/compactness#3]
https://github.com/aaronrkaufman/compactness/blob/4e217d54ad9405d5ed78dd9697140d8f20035049/R/read_shapefiles.R#L22-L35

If there are only 2 columns, `metadata[,-ncol(metadata)]` will convert metadata into a factor rather than keep it as a dataframe, creating errors downstream.

You could wrap it in an `as.data.frame` to be sure or use the `subset` function which is also still base R and maintains the class of your result.

**Comment by aaronrkaufman** [comment]
Thanks! I've made the change.
