### ISSUE TITLE
Dependency on `raster` library

### ISSUE THREAD

**Issue by maxblee** [aaronrkaufman/compactness#5]
Hi, thank you so much for creating this repository and making it open source. I tried to run the `get_compactness` function and got the following error:

```sh
generic:  Error in loadNamespace(name): there is no package called ‘raster’
```

The root cause of this is presumably that the `raster` library does not appear to be imported in `NAMESPACE` but is used in [`get_one_symmetry_noncontig`](https://github.com/aaronrkaufman/compactness/blob/master/R/feature_helpers.R#L134). Am I correct in assuming that I should just fix this using

```r
install.packages("raster")
```

If so, would you mind patching that? Thanks!

**Comment by aaronrkaufman** [comment]
You are correct on both counts! I've added raster to be imported in NAMESPACE. Thanks for this!
